---
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
---

# sf와 stars {#sec-sf-stars}

이 장에서는 R 패키지인 **sf**와 **stars**를 소개한다. **sf**는 피처의 기하 정보를 리스트-컬럼에 저장하는 단순 피처의 테이블 포맷을 제공한다. **stars** 패키지는 래스터와 벡터 데이터 큐브(6장에서 다룸)를 지원하기 위해 작성되었으며, 래스터 레이어, 래스터 스택 및 피처 시계열 또한 지원한다. **sf**는 2016년에 CRAN에 처음 등장했고, **stars**는 2018년에 등장했다. 두 패키지의 개발은 R 컨소시엄의 지원과 강력한 커뮤니티 참여로 이루어졌다. 이 패키지들은 함께 작동하도록 설계되었다. **sf**나 **stars** 객체를 대상으로 하는 함수 또는 메서드는 `st_`로 시작하는데, 쉽게 관련 함수를 인식할 수 있을 뿐만 아니라 명령어 완성 기능을 사용할 때 검색의 용이함이 있다.

## sf 패키지 {#sec-sf}

### 생성

### 불러오기와 쓰기 

### 부분을 골라내기

### 바이너리 프레디케이트

### 타이디버스

## 공간적 조인

### 샘플링, 그리딩, 인터폴레이팅

## 타원좌표

## stars 패키지 

### 래스터 데이터의 불러오기와 쓰기

### stars 데이터 큐브 일부분 골라내기

### 잘라내기

### stars 객체를 차원 다시 부여하기와 결합하기

### 포인트 샘플 추출하기, 애그리게이팅하기

### 예측 모델

### 래스터 데이터 플로팅

### 래스터 데이터 분석하기

### 곡선 래스터

### GOAL utils

## 벡터 데이터 큐브 사례

### 사례: 대기질 시계열 애그리게이팅하기 

### 사례: 브리스톨 출발지-도착지 데이터 큐브

### 타이디 어레이 데이터

### 벡터 데이터 큐브를 위한 파일 포멧

## 래스터-투-벡터와 벡터-투-래스터

### 벡터-투-래스터

## 좌표변환 및 좌표전환

### 데이텀 그리드, proj.db, cdn.proj.org. 로컬 캐쉬

### 변환 파이프라인

### 축 순서와 방향

## 래스터 변환 및 워프

## 연습문제
