---
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
---

# 포인트 패턴 분석 {#sec-point}

포인트 패턴 분석은 공간 상의 포인트 패턴을 기술하거나 그러한 패턴을 야기한 프로세스에 대한 추론을 행한다. 여기서 핵심적인 사항은 포인트들의 위치 정보인데, 이러한 위치는 샘플링을 위한 통제 지점이 아니라, 특정한 프로세스의 산물(동물 목격 지점, 사고 지점, 발병 지점, 수목 지점 등)이다. 이것은 모든 지점에서 해당 현상이 발생하지만 관측값은 우리가 통제한 관측 지점에서만 획득된 것이라고 보는 지구통계학적 프로세스(12장)와 대조된다. 그러므로, 지구통계학적 연구의 주된 관심은 관측 지점에 있는 것이 아니라 비관측 지점의 값을 추정하는 데 있다. 포인트 패턴 분석은 해당 지역의 모든 지점에서 관측이 이루어질 수 있다고 가정한다. 이는 특정 지점에 포인트가 없다면 해당 지점에서 관측이 이루어지지 않았다는 것이 아니라(지구통계학적 프로세스) 관측은 이루어졌지만 현상이 발생하지 않았다는 것을 의미한다. 확률 과정(random process)의 용어로 말하자면, 포인트 패턴 분석에서 위치는 확률 변수이지만, 지구통계학적 분석에서 측정 변수는 고정 위치를 가진 랜덤 필드이다.

이 장에서는 **spatstat** 패키지(Baddeley, Turner, Rubak 2022)를 활용한 포인트 패턴 분석의 기초만을 다룬다. 포인트 패턴 이론과 **spatstat** 및 관련 패키지의 사용에 대한 포괄적인 내용은 Baddeley, Rubak, Turner(2015)의 **spatstat** 책에 잘 나타나 있다. 이 장에서는 특정 주제만을 다루게 되는데, 해당 주제가 누락된 주제에 비해 더 중요하다는 의미는 전혀 아니다. **spatstat** 패키지와 보다 공간데이터사이언스 지향 패키지인 **sf** 및 **stars** 간의 인터페이스를 설명하는데 공간을 할애하려 한다. 포인트 패턴 분석을 소개하는 또 다른 책으로는 Stoyan et al.(2017)가 있다. 시공간 포인트 프로세스 분석용 R 패키지인 **stpp**(Gabriel et al. 2022)에 대한 내용은 Gabriel, Rowlingson, Diggle(2013)를 참고할 수 있다.

포인트 패턴 분석에서 중요한 개념은 포인트 *패턴*과 포인트 *프로세스*를 구분하는 것이다. 포인트 프로세스는 포인트 패턴을 생성하는 확률 과정(stochastic process)이다. 데이터셋은 항상 포인트 패턴이며, 추론은 우리가 관찰한 패턴을 생성할 수 있는 프로세스의 특성을 파악하는 것이다. 공간 포인트 프로세스의 특성에는 다음이 포함된다.

-   1차 특성: 강도 함수는 단위 면적당 포인트의 수를 측정하며, 이 함수는 *이질적*(inhomogeneous) 포인트 프로세스의 경우 공간적으로 변동한다.

-   2차 특성: 주어진 강도 함수(고정 혹은 변동) 하에서, 포인트들이 *서로* 독립적으로 분포하는지, 서로 끌어당기는 경향이 있는지(군집화), 또는 서로 밀어내는 경향이 있는지(완전 공간 무작위성(complete spatial randomness)보다 더 규칙적으로 분포하는지)를 묘사한다.

## 관측 윈도우

## CRS

## 속성이 있는 포인트 패턴, 선형 네트워크 상의 포인트

## 공간 샘플링과 포인트 프로세스를 시뮬레이션하기

## 구체 상의 포인트를 시뮬레이션하기

## 연습문제
