---
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
---

# 공간적 회귀분석 {#sec-regression}

에어리어 서포트를 가지는 한 변수가 주어졌을 때 그것이 보여주는 공간적 패턴의 해석에 집중하는 것은 의미있는 일이다. 그러나 해당 변수의 공간적 패턴을 설명하고자 한다면, 즉 해당 변수를 반응 변수로 간주한다면 얘기는 좀 달라진다. 왜냐하면 반응 변수과 보여주는 공간적 패턴을 주로 공변량(및 그 함수 형태)에 기인한 것일 가능성이 크고, 개별 변수의 영향력이 작동하는 공간적 범위에 영향을 받기 때문이다. 이차원 공간적 자기회귀 모델은 공변량 없이 시작되었으며, 시계열 분석 모델과 명확한 연관성을 가지고 있다(Whittle, 1954). 이후 선형 모델 잔차에서 공간적 자기상관을 검정하는 방법과 자기회귀 성분을 반응 변수나 잔차에 적용하는 모델로 확장되었는데, 자기회귀 성분을 잔차에 적용하는 모델은 잔차에 대한 검정과 일치하는 것이었다(Cliff and Ord, 1972, 1973). 이러한 에어리어 데이터에 대한 "격자(lattice)" 모델은 일반적으로 연접성 행렬 형태의 이웃 관계 그래프를 사용하여 관측값 간의 공간적 의존성을 나타낸다.

물론, 일반화 최소제곱 모델이나 **nlme** 및 기타 여러 패키지에서 제공하는 (일반화) 선형 또는 비선형 혼합효과 모델에서 공간적 자기상관을 다루는 데 반드시 이웃 관계 그래프를 사용할 필요는 없다(Pinheiro and Bates, 2000). 관측값 간의 거리 함수를 사용하거나 공간적 자기상관을 모델링하기 위해 베리오그램을 적합하는 것 역시 공간적 회귀 모델의 일종이라고 말할 수 있다. 이러한 접근은 기저 과정에 대한 더 명확한 이해를 제공한다고 평가되었으며(Wall, 2004), 지구통계학에 기반을 두고 있다. 예를 들어, **glmmTMB** 패키지는 이 접근법을 활용해 공간적 회귀분석을 성공적으로 수행한다(Brooks et al., 2017). 하지만 본 장에서는 공간 가중치 행렬을 사용하는 공간적 회귀분석만을 고려할 것이다.

## 마르코프 랜덤 필드와 다수준 모델

질병 지도화(disease mapping) 연구에서는 공간적으로 구조화된 임의 효과를 다루기 위해 조건부(conditional) 자기회귀(CAR) 모델과 내재적(intrinsic) 자기회귀(ICAR) 모델을 사용하는 광범위한 연구가 존재한다. 이러한 모델은 다수준 모델로 확장될 수 있으며, 공간적으로 구조화된 임의 효과가 모델의 서로 다른 수준에서 적용될 수 있다(Bivand et al., 2017). 여러 변형을 시도하기 위해, 우리는 트랙트(tract) 수준과 모델 출력 구역 집계(model output zone aggregated) 수준을 두 단계로 나누어 이웃이 없는 관측값을 제거해야 한다. 트랙트 수준에서 이웃 관계가 줄어들면 모델 출력 구역 수준에서도 이웃이 없는 결과가 발생할 수 있기 때문이다. 모델 추정 함수의 대부분은 `family` 아규먼트를 사용하며, 이웃 간 관계를 마르코프 랜덤 필드로 표현한 공간 랜덤 효과를 통해 각 관측값에 대해 일반화 선형 혼합효과 모델을 적합한다. 다수준 모델의 경우, 랜덤 효과는 그룹 수준에서 모델화될 수 있으며, 아래의 예시에 적용되어 있다.

공간적 회귀분석을 혼합 효과 모델에 의거해 설명하는 Pinheiro and Bates (2000)와 McCulloch and Searle (2001)의 논리가 중요한데, Gómez-Rubio (2019)의 표현식을 딸라 설명하고자 한다. 반응 변수 $Y$, 고정 공변량 $X$, 회귀계수 $\beta$, 오차 항 $\epsilon_i\sim N(0, \sigma^2), i=1,...,n$이 주어진 상태에서 랜덤 효과 $u$가 첨가되면, 가우시안 선형 혼합 효과 모델은 다음과 같이 정의된다.

$$
Y=X\beta+Zu+\epsilon
$$

여기서 $Z$는 랜덤 효과를 위한 고정 디자인 행렬이다. 만약 $n$개의 랜덤 효과가 있다면, $n \times n$ 단위 행렬이 되고, 만일 관측값이 $m$개의 그룹으로 집계되어 $m<n$의 랜덤 효과만 있다면 각 관측값이 어느 그룹에 속하는지를 나타내는 $n \times m$행렬이 된다. 랜덤 효과는 다변량 정규 분포 $u\sim N(0,\sigma_u^2 \sum)$로 모델화되며, $\sigma_u^2 \sum$은 랜덤 효과의 분산-공분산 행렬이다.

CAR 모델(Besag, 1974)과 SAR(simultaneous autoregressive) 모델(Ord, 1975; Hepple, 1976)이 분리되어 발전해 왔는데, 이러한 구분의 유익함은 사실 별로 없다. CAR 모델과 SAR 모델은 밀접하게 연관되어 있음에도 불구하고 , 이 두 분야는 유사한 모델을 적용하는 경험을 공유하는데 어려움을 겪고 있다. 이러한 어려움은 CAR과 SAR 모델을 정리한 핵심 저작(Ripley, 1981, 1988; Cressie, 1993)을 참고하는 경우에도 마찬가지이다. Ripley는 SAR의 분산을 제시한 바 있는데(Ripley, 1981, 89), 여기서는 $\sum^{-1}$(정밀도 행렬로도 알려짐)로 나타낸다.

$$
\Sigma^{-1}=[(I-\rho W)'(I-\rho W)]
$$

여기서 $\rho$는 공간적 자기상관 파라미터이고, $W$는 공간적 의존성을 나타내는 비단일(non-singular) 공간 가중치 행렬이다. CAR 분산을 다음과 같이 주어진다.

$$
\Sigma^{-1}=(I=\rho W)
$$

여기서 $W$는 대칭적이고 엄격히 양의 정의인 공간 가중치 행렬이다. 내재적 CAR 모델의 경우, 공간적 자가상관 파라미터를 추정하지 않으며 다음과 같은 형태로 주어진다.

$$
\Sigma^{-1}=M=\text{diag}(n_i)-W
$$

여기서 $W$는 앞서 언급한 것처럼 대칭적이고 엄격히 양의 정의인 공간 가중치 행렬이며,\
$n_i$은 $W$의 행 합산값을 나타낸다. Besag-York-Mollié 모델은 내재적 CAR 공간 구조화된 랜덤 효과와 비구조화된 랜덤 효과를 포함한다. Leroux 모델은 비구조화된 랜덤 효과와 공간 구조화된 랜덤 효과의 행렬 구성 요소를 결합하며, 공간 구조화된 랜덤 효과는 내재적 CAR의 정의를 따르는 것으로 간주된다.

$$
\Sigma^{-1}=[(1-\rho)I_n+
\rho M]
$$

이 모델들의 정의에 대해서는 Gómez-Rubio (2020)를 참조할 수 있고, Besag-York-Mollié와 Leroux 모델에 영향을 미치는 추정 문제에 대해서는 Gerber and Furrer (2015)에서 다루어진다.

에어리어 데이터 모델링의 이론적 기초를 다루고 있는 최근의 서적(Gaetan and Guyon, 2010; Van Lieshout, 2019)은 SAR 모델과 CAR 모델의 유사성을 몇몇 장에서 지적하고 있다. 배경 정보에 관심이 있는 독자는 이 서적들을 참고하면 된다.

### 보스턴 주택가격 데이터셋

## 보스턴 데이터셋에 대한 다수준 모델

### IID 랜덤 효과: lme4 패키지의 활용

### IID와 CAR 랜덤 효과: hglm 패키지의 활용

### IID와 ICAR 랜덤 효과: R2BayesX 패키지의 활용

### IID, ICAR, Lerouzx 랜덤 효과: INLA 패키지의 활용

### ICAR 랜덤 효과: mgcv 패키지의 gam() 함수의 활용

### 상위-수준 랜덤 효과: 요약

## 연습문제
