project:
  type: book
  output-dir: docs

lang: ko

book:
  title: "공간데이터사이언스 개론"
  subtitle: "R 프로그래밍 예시"
  author: 
    - name: 이상일
      orcid: 0000-0002-5342-9930
      email: si_lee@snu.ac.kr
      url: https://sangillee.snu.ac.kr/
      affiliations:
        - name: 서울대학교 지리교육과
          url: https://geoedu.snu.ac.kr/
          city: Seoul
          country: South Korea
  date: last-modified
  search: true
  bread-crumbs: false
  back-to-top-navigation: true
  repo-url: https://github.com/sangillee66/book_sds_trans
  repo-actions: [issue]
  chapters:
    - index.qmd
    - part: part_1.qmd
      chapters: 
        - 01.qmd
        - 02.qmd
        - 03.qmd
        - 04.qmd
        - 05.qmd
        - 06.qmd
    - part: part_2.qmd
      chapters: 
        - 07.qmd
        - 08.qmd
        - 09.qmd
    - part: part_3.qmd
      chapters: 
        - 10.qmd
        - 11.qmd
        - 12.qmd
        - 13.qmd
        - 14.qmd
        - 15.qmd
        - 16.qmd
        - 17.qmd
  appendices:
    - A.qmd
    - B.qmd
#    - references.qmd

# filters: 
#  - endnotes-per-chapter.lua

bibliography: references.bib

lightbox: true

execute:
  freeze: auto

format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    number-sections: true
    number-depth: 3
    code-link: true
    toc: true
    fig-title: "그림"
    table-title: "표"
    chapter-title: "장"
  docx:
    toc: true
    toc-depth: 3
    number-sections: true

editor: visual

profiles: 
  docx:
    book: 
      project:
        output-dir: _docx
      execute:
        freeze: true
      chapters:
        - index.qmd
        - part_1_docx.qmd
        - 01.qmd
        - 02.qmd
        - 03.qmd
        - 04.qmd
        - 05.qmd
        - 06.qmd
        - part_2_docx.qmd
        - 07.qmd
        - 08.qmd
        - 09.qmd
        - part_3_docx.qmd
        - 10.qmd
        - 11.qmd
        - 12.qmd
        - 13.qmd
        - 14.qmd
        - 15.qmd
        - 16.qmd
        - 17.qmd      
      appendices: # 이 부분을 추가합니다.
        - A.qmd
        - B.qmd
    
    format:
      docx:
        toc: true
        toc-depth: 3        
        number-sections: true
