---
date-modified: last-modified
number-sections: true
format: 
  html: 
    toc: true
code-link: true
code-copy: true
execute: 
  warning: false
  error: false
  freeze: auto
editor: visual
---

# 공간통계분석과 공간모델링

이 책의 첫 번째 파트와 두 번째 파트에서는 '공간데이터 모델'과 관련된 많은 개념에 대해 알아보았다. 다음의 주제들이 다루어졌다.

-   실제 현상과 숫자의 관계(2장)

-   다양한 공간에서 좌표가 정의되는 방식(2장과 4장)

-   단순 피처 지오메트리(3장), 두 점 사이의 직선을 이용해 라인스트링과 폴리곤을 정의하는 방법

-   지오메트리 유형의 집합(3.1절)

-   서포트 및 피처 속성과 지오메트리의 관련 방식(5장)

-   단순 테셀레이션이 시공간 체적(볼륨)을 설명하는 방식(6장)

-   이 개념들을 데이터사이언스 소프트웨어로 적용하는 방법(7장)

이 책의 세 번째이자 가장 분량이 많은 이 파트에서는 공간데이터의 *통계적* 모델링을 다룬다. 과학으로서 *통계학*은 관측값의 변동성을 기술하고 이해하며, 미래 관측값을 예측하는 데 중점을 둔다. 관측값은 보통 다음과 같이 모델링된다.

$$
\text{관측값}=\text{설명된 부분}+\text{잔차}
$$

여기서 "잔차"는 측정 오차를 포함한 예측 변수로 설명되지 않는 변동성을 의미할 뿐만 아니라 낮은 모델 적합도 또는 모델 오지정(missification)이 야기한 변동성을 의미한다. 공간데이터의 경우, 다음과 같이 항이 하나 더 추가된다.

$$
\text{관측값}=\text{설명된 부분}+\text{매끄러운 부분}+\text{잔차}
$$

여기서 "매끄러운 부분"은 외부 예측 변수로는 설명되지 않지만, 명확하게 "매끄러운" 공간 패턴을 보여주는 변동성을 의미하며, "잔차"는 이러한 패턴을 나타내지 않는 "거친" 변동성을 의미한다. 이러한 "매끄러운" 항은 예를 들어 좌표상의 기본 함수(스플라인, 스무더)로 모델링하거나, 공간적 상관성을 띠는 랜덤 항으로 모델링할 수 있다.

10장에서는 공간데이터에 대한 통계적 모델링을 소개한다. 이를 통해 후속 장을 준비하는 동시에, 후속 장에서는 자세히 다루지 않는 여러 사항을 다룬다. 또한 이 장은 첫번째 파트에서 다룬 개념들, 특히 5장에서 다룬 '서포트' 개념과의 연결을 시도한다.

공간 데이터의 통계적 모델링에 대한 상세한 내용 뿐만 아니라 전산 소프트웨어의 사용 방법에 대한 세세한 내용까지를 단 한 권의 책에 모두 담는 일은 애당초 불가능하다. 예를 들어, `spatstat` 책(Baddeley, Rubak, and Turner, 2015)은 오직 공간 포인트 패턴 데이터와 R에 대한 내용만을 다루는데도 분량이 약 850페이지에 달한다. 이 세 번째 파트에서는 '고전적인' 공간통계학적 주제 세 가지에 집중한다: 포인트 패턴 분석(11장), 지구통계학적 데이터(12장, 13장), 그리고 래티스(지역) 데이터(14-17장). 내용 중간중간에 통계 방법론 및 R 실행과 관련된 참고 사항을 가능한 많이 제시하도록 노력할 것이다.
